image:
  repository: pong-service
  tag: "v1"
  pullPolicy: Never # Minikube-hoz kötelező, ha helyben buildeltél!

service:
  type: ClusterIP # Csak belső elérés
  port: 8081

istio:
  gateway:
    enabled: false
  virtualService:
    enabled: false